import { defineStore } from "pinia";
import type { DragonEditorStore, DEOption } from "../type.mjs";

export const useEditorStore = defineStore("editorStore", {
    state: (): DragonEditorStore => ({
        data: [],
        selectedBlockId: "",
        selectedBlockIndex: -1,
        status: {
            isParentOverflowHidden: false,
            isImageResizeActive: false,
            anchorHerf: "",
            menuTop: 0,
        },
        option: {
            mediaHostURL: "",
            isMobile: false,
            codeBlockSpaces: 4,
            acceptImageFormat: "",
            anchorTagTarget: "",
        },
        cursorSelection: null,
        cursorRange: null,
        element: {
            body: null,
            editor: null,
            scrollParentElement: null,
        },
        fn: {
            updateEditorData: null,
            uploadImage: null,
        },
        codeBlockLnaguageList: {
            text: "Plain Text",
            markdown: "Markdown",
            html: "HTML, XML",
            vue: "Vue",
            jsx: "Jsx",
            tsx: "Tsx",
            css: "CSS",
            scss: "SCSS",
            json: "JSON",
            javascript: "JavaScript",
            typescript: "TypeScript",
            dockerfile: "Dockerfile",
            go: "Go",
            java: "Java",
            kotlin: "Kotlin",
            php: "PHP",
            python: "Python",
            ruby: "Ruby",
            lua: "Lua",
            csharp: "C#",
            c: "C",
            cpp: "C++",
            nginx: "Nginx",
            sql: "SQL",
            shellscript: "Shell",
            swift: "Swift",
            yaml: "YAML",
        },
    }),
    actions: {},
});
