export enum DECodeLanguage {
    text = "Plain Text",
    csharp = "C#",
    c = "C",
    cpp = "C++",
    css = "CSS",
    dockerfile = "Dockerfile",
    go = "Go",
    html = "HTML, XML",
    json = "JSON",
    java = "Java",
    javascript = "JavaScript",
    typescript = "TypeScript",
    kotlin = "Kotlin",
    lua = "Lua",
    markdown = "Markdown",
    nginx = "Nginx",
    php = "PHP",
    python = "Python",
    ruby = "Ruby",
    scss = "SCSS",
    sql = "SQL",
    shellscript = "Shell",
    swift = "Swift",
    yaml = "YAML",
}
